FROM node:22-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json ./

RUN yarn install --production --timeout=600000

COPY . .

# RUN yarn run build

EXPOSE 5009


CMD [ "yarn","start"]