apiVersion: v1
kind: Deployment
metadata:
  name: lab-deployment
  labels: 
    app: labapp
    # type: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labapp
    template:
      metadata:
        labels:
          app: labapp  
  spec:
    containers:
    - name: labservice
      image: blackwell18/lab:latest
      ports:
      - containerPort: 3001    # resources:
      #   limits:
      #     memory: 512Mi
      #     cpu: "1"
      #   requests:
      #     memory: 256Mi
      #     cpu: "0.2"