# Generated by Django 5.0.6 on 2024-07-17 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('dob', models.DateField(auto_now_add=True)),
                ('phoneNo', models.CharField(max_length=100)),
                ('idNo', models.CharField(max_length=100)),
                ('cccNo', models.CharField(max_length=100, unique=True)),
                ('ageAtReporting', models.CharField(max_length=100)),
                ('dateConfirmedPositive', models.DateField(auto_now_add=True)),
                ('initialRegimen', models.CharField(max_length=100)),
                ('populationType', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='ArtPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('regimen', models.CharField(max_length=100)),
                ('isStandard', models.BooleanField()),
                ('line', models.CharField(max_length=100)),
                ('changeReason', models.CharField(max_length=100)),
                ('stopReason', models.CharField(max_length=100)),
                ('changeDate', models.DateTimeField(auto_now_add=True)),
                ('stopDate', models.DateTimeField(auto_now_add=True)),
                ('patientID', models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='linelist_api.patients')),
            ],
            options={
                'db_table': 'artPrescriptions',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('noOfPills', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('refillDate', models.DateTimeField(auto_now_add=True)),
                ('nextRefillDate', models.DateTimeField(auto_now_add=True)),
                ('expectedNoOfPills', models.IntegerField()),
                ('computedNoOfPills', models.IntegerField()),
                ('updatedAtExpectedNoOfPills', models.DateTimeField(auto_now_add=True)),
                ('artPrescriptionID', models.ForeignKey(db_column='artPrescriptionID', on_delete=django.db.models.deletion.CASCADE, to='linelist_api.artprescription')),
                ('patientID', models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='linelist_api.patients')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='ViralLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vlResults', models.IntegerField(default=0, null=True)),
                ('vlJustification', models.CharField(max_length=100)),
                ('dateOfVL', models.DateTimeField(auto_now_add=True)),
                ('dateOfNextVL', models.DateTimeField(auto_now_add=True)),
                ('patientID', models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='linelist_api.patients')),
            ],
            options={
                'db_table': 'viralLoads',
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('weight', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('patientID', models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='linelist_api.patients')),
            ],
            options={
                'db_table': 'vitalSigns',
            },
        ),
    ]
