# Generated by Django 5.0.6 on 2024-06-22 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('dob', models.DateField(auto_now_add=True)),
                ('phoneNo', models.CharField(max_length=100)),
                ('idNo', models.CharField(max_length=100)),
                ('occupationID', models.CharField(max_length=100)),
                ('cccNo', models.CharField(max_length=100, unique=True)),
                ('ageAtReporting', models.CharField(max_length=100)),
                ('dateConfirmedPositive', models.DateField(auto_now_add=True)),
                ('initialRegimen', models.CharField(max_length=100)),
                ('populationType', models.CharField(max_length=100)),
                ('schoolID', models.CharField(max_length=100)),
                ('hospitalID', models.CharField(max_length=100)),
                ('entryPoint', models.CharField(max_length=100)),
                ('subCountyName', models.CharField(max_length=100)),
                ('maritalStatus', models.CharField(max_length=100)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('regimen', models.CharField(max_length=100)),
                ('isStandard', models.BooleanField()),
                ('line', models.CharField(max_length=100)),
                ('changeReason', models.CharField(max_length=100)),
                ('stopReason', models.CharField(max_length=100)),
                ('changeDate', models.DateTimeField(auto_now_add=True)),
                ('stopDate', models.DateTimeField(auto_now_add=True)),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linelist_api.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regimen', models.CharField(max_length=100)),
                ('noOfPills', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('refillDate', models.DateTimeField(auto_now_add=True)),
                ('nextRefillDate', models.DateTimeField(auto_now_add=True)),
                ('expectedNoOfPills', models.IntegerField()),
                ('computedNoOfPills', models.IntegerField()),
                ('updatedAtExpectedNoOfPills', models.DateTimeField(auto_now_add=True)),
                ('artPrescriptionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linelist_api.artprescription')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linelist_api.patients')),
            ],
        ),
        migrations.CreateModel(
            name='ViralLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vlResults', models.IntegerField(default=0, null=True)),
                ('vlJustification', models.CharField(max_length=100)),
                ('dateOfVL', models.DateTimeField(auto_now_add=True)),
                ('dateOfNextVL', models.DateTimeField(auto_now_add=True)),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linelist_api.patients')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('weight', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linelist_api.patients')),
            ],
        ),
    ]
