# Generated by Django 5.0.6 on 2024-06-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linelist_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='nextRefillDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='refillDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='updatedAtExpectedNoOfPills',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
