# Generated by Django 5.0.6 on 2024-11-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linelist_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artprescription',
            name='changeDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='artprescription',
            name='startDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='artprescription',
            name='stopDate',
            field=models.DateTimeField(),
        ),
    ]
