# Generated by Django 5.0.6 on 2024-07-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linelist_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artprescription',
            table='artPrescriptions',
        ),
        migrations.AlterModelTable(
            name='patients',
            table='patients',
        ),
        migrations.AlterModelTable(
            name='prescription',
            table='prescriptions',
        ),
        migrations.AlterModelTable(
            name='viralload',
            table='viralLoads',
        ),
        migrations.AlterModelTable(
            name='vitalsigns',
            table='vitalSigns',
        ),
    ]
