# Generated by Django 5.0.6 on 2024-07-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linelist_api', '0002_alter_artprescription_table_alter_patients_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artprescription',
            name='patientID',
            field=models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='linelist_api.patients'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='artPrescriptionID',
            field=models.ForeignKey(db_column='artPrescriptionID', on_delete=django.db.models.deletion.CASCADE, to='linelist_api.artprescription'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patientID',
            field=models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='linelist_api.patients'),
        ),
        migrations.AlterField(
            model_name='viralload',
            name='patientID',
            field=models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='linelist_api.patients'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='patientID',
            field=models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='linelist_api.patients'),
        ),
    ]
