# Generated by Django 5.0.6 on 2024-06-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linelist_api', '0002_alter_patients_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viralload',
            name='vlResults',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
