# Generated by Django 5.0.6 on 2024-07-18 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linelist_api', '0003_csvfile_createdat_csvfile_updatedat_facilitymaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
