# Generated by Django 5.0.6 on 2024-07-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linelist_api', '0003_alter_artprescription_patientid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='regimen',
        ),
    ]
