# Generated by Django 5.0.6 on 2024-07-18 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linelist_api', '0004_alter_csvfile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitymaps',
            name='ageGroup',
        ),
        migrations.RemoveField(
            model_name='facilitymaps',
            name='count',
        ),
        migrations.RemoveField(
            model_name='facilitymaps',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='facilitymaps',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='facilitymaps',
            name='regimen',
        ),
        migrations.RemoveField(
            model_name='facilitymaps',
            name='regimenLine',
        ),
        migrations.RemoveField(
            model_name='facilitymaps',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='facilitymaps',
            name='details',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
