# Generated by Django 5.0.6 on 2024-07-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linelist_api', '0004_remove_prescription_regimen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='entryPoint',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='hospitalID',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='location',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='maritalStatus',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='occupationID',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='schoolID',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='subCountyName',
        ),
    ]
