# Generated by Django 5.0.6 on 2024-07-18 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linelist_api', '0005_remove_facilitymaps_agegroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitymaps',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilitymaps',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
